# Generated by Django 4.1.4 on 2022-12-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_dataanalysis_unique station data for particular year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corn_grain_yield',
            new_name='CornGrainYield',
        ),
        migrations.RenameModel(
            old_name='DataAnalysis',
            new_name='WeatherAnalysis',
        ),
    ]